# Site settings
title: Deltron 3030
email: swashcap@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Selected lyrics from the seminal album.
baseurl: "/deltron-3030/" # the subpath of your site, e.g. /blog/
url: "http://swashcap.github.io" # the base hostname & protocol for your site
twitter_username: swashcap
github_username:  swashcap

# Build settings
markdown: kramdown
